/*
 * OpenSource EBike firmware
 *
 * Copyright (C) Stancecoke, 2017.
 *
 * Released under the GPL License, Version 3
 */

#include <stdint.h>
#include "stm8s.h"
#include "gpio.h"
#include "interrupts.h"
#include "SPEED.h"
#include "config.h"

volatile uint16_t ui16_wheel_rotation_per_msec = UINT16_MAX;
volatile uint8_t  ui8_wheel_rotation_per_sec = 0;

void timer3_init(void) {
    // 1. Enable peripheral clock for TIM3
    CLK->PCKENR1 |= CLK_PCKENR1_TIM3;

    // Prescaler: 2^14 = 16,384. (16MHz / 16384 = 976.5Hz)
    TIM3->PSCR = 0x0E; 

    // Max out ARR so it counts all the way to 65535 milliseconds before resetting
    TIM3->ARRH = 0xFF;
    TIM3->ARRL = 0xFF;

    // Setting the OPM bit means the timer stops counting immediately upon hitting ARR
    TIM3->CR1 |= TIM3_CR1_OPM;

    // No interrupts
    TIM3->IER |= 0x00; 

    // Start the timer.
    TIM3->CR1 |= 0x01; 
}

// Wheel revolution interrupt signal
void EXTI_PORTC_IRQHandler(void) __interrupt(EXTI_PORTC_IRQHANDLER)
{

   // 1. Read the 16-bit hardware counter (High byte first!)
    uint16_t current_time = ((uint16_t)TIM3->CNTRH << 8) | TIM3->CNTRL;

    // 2. Check if the timer stopped (Timeout > 65.5 seconds)
    // If CEN is 0, One-Pulse Mode triggered, meaning the timer rolled over to 0.
    if ((TIM3->CR1 & TIM3_CR1_CEN) == 0) {
        // The wheel took longer than 65 seconds. 
        // You can set this to 0xFFFF or 0 depending on how you want to handle a stopped wheel.
        ui16_wheel_rotation_per_msec = 0xFFFF; 
    }
    // 3. Software Debounce check
    // If the time is less than 10ms, it's physically impossible for the wheel 
    // to have made a full rotation. It must be switch bounce noise! Ignore it.
    else if (current_time > 10) {
        // Valid rotation! Save the time.
        ui16_wheel_rotation_per_msec = current_time;
    }

    ui8_wheel_rotation_per_sec = 976 / ui16_wheel_rotation_per_msec;

    TIM3->EGR |= TIM3_EGR_UG; 

    // 3. Clear the update flag generated by the forced reset
    TIM3->SR1 &= ~TIM3_SR1_UIF;

    // 4. Crucial for One-Pulse Mode: Re-enable the timer (CEN) 
    // This turns the clock back on if it frozen at the max value
    TIM3->CR1 |= TIM3_CR1_CEN;    

}

void SPEED_init (void)
{
    //Wheel revolution pin as external input pin interrupt
    GPIO_Init(SPEED__PORT,
              SPEED__PIN,
              GPIO_MODE_IN_PU_IT); // with Pullup and external interrupt

    //initialize the Interrupt sensitivity: falling edge only
    EXTI_SetExtIntSensitivity(EXTI_PORT_GPIOC,
                              EXTI_SENSITIVITY_FALL_ONLY);
}


